import {
  WiDayStormShowers,
  WiDaySunny,
  WiCloudy,
  WiDayRainMix,
  WiDayRain,
  WiDaySnow,
  WiTornado,
  WiFog,
  WiDust,
  WiDayFog,
  WiSmoke,
  WiNightAltStormShowers,
  WiNightAltRainMix,
  WiNightClear,
  WiNightAltCloudy,
  WiNightAltRain,
  WiNightAltSnow,
  WiNightFog,
} from 'weather-icons-react';

export const weatherIconDay = {
  Thunderstorm: <WiDayStormShowers size={70} color="white" />,
  Drizzle: <WiDayRainMix size={70} color="white" />,
  Rain: <WiDayRain size={70} color="white" />,
  Snow: <WiDaySnow size={70} color="white" />,
  Tornado: <WiTornado size={70} color="white" />,
  Clear: <WiDaySunny size={80} color="white" />,
  Mist: <WiFog size={70} color="white" />,
  Smoke: <WiSmoke size={70} color="white" />,
  Haze: <WiDayFog size={70} color="white" />,
  Dust: <WiDust size={70} color="white" />,
  Ash: <WiDust size={70} color="white" />,
  Squall: <WiDayStormShowers size={70} color="white" />,
  Clouds: <WiCloudy size={70} color="white" />,
};

export const weatherIconNight = {
  Thunderstorm: <WiNightAltStormShowers size={70} color="white" />,
  Drizzle: <WiNightAltRainMix size={70} color="white" />,
  Rain: <WiNightAltRain size={70} color="white" />,
  Snow: <WiNightAltSnow size={70} color="white" />,
  Tornado: <WiTornado size={70} color="white" />,
  Clear: <WiNightClear size={80} color="white" />,
  Mist: <WiFog size={70} color="white" />,
  Smoke: <WiSmoke size={70} color="white" />,
  Haze: <WiNightFog size={70} color="white" />,
  Dust: <WiDust size={70} color="white" />,
  Ash: <WiDust size={70} color="white" />,
  Squall: <WiNightAltStormShowers size={70} color="white" />,
  Clouds: <WiNightAltCloudy size={70} color="white" />,
};
